### ISSUE TITLE
Main Form needs Three Buttons.

### ISSUE THREAD

**Issue by shawnkoon** [shawnkoon/Smart-GPA-Calculator#2]
Main Form needs to display

Program Title

button 1 (Cumulative  GPA)
button 2 (Single Class GPA)
button 3 (About)

When the buttons are pressed it should call showDialog() method such that mainForm will be disabled until they close the new forms.

**Comment by kwelsch7** [comment]
Should we add a button for "Single Term GPA"? So
Cumulative = All classes taken at Institution
Single Term = Quarter or Semester
Single Class = Well...that
