### ISSUE TITLE
Term Overview Area

### ISSUE THREAD

**Issue by kwelsch7** [shawnkoon/Smart-GPA-Calculator#8]
Needs to be dynamic (to support different number of terms)

**Comment by shawnkoon** [comment]
what is this mean? any examples?

**Comment by kwelsch7** [comment]
You can refer to the Design drawing (which I posted on here) for a more visual view, but we need it do be able to display
Fall 2015 - Quarter
CSCD 210                       3.9/4.0
Programming Principles 1
etc.
Winter 2016 - Quarter
CSCD 211                       4.0/4.0
Programming Principles 2
etc.
....
without putting in a bunch of static Label tools
