### ISSUE TITLE
Pre-populating Values

### ISSUE THREAD

**Issue by kwelsch7** [shawnkoon/Smart-GPA-Calculator#9]
After having submitted at least one class, we may want to consider pre-populating things like the drop-downs with the values previously used or the "Out of 4.0 Scale" (So that they can add classes to the same term with a little less hassle).

**Comment by shawnkoon** [comment]
Yeah that sounds like a good idea. Also that will force users to enter numbers in x.x scale instead of making one of the class to be x.y scale.
